# -*- coding: utf-8 -*-
"""Streamline_print_statements_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3rfr-tWdWXIjdnS4-HYlWvQcLu-JjUx

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Streamline your print statements

In this lesson, we'll explore the importance of clear and informative print statements in Python, practising three string formatting methods – concatenation, `format()`, and formatted string literals (f-strings).

## Learning objectives

By the end of this train, you should be able to:
- Understand how well-structured print statements improve code readability and collaboration among developers.
- Differentiate between concatenation, the `format()` method, and f-strings, and how to apply them to format and print statements.

## Outline
1. [Introduction](#introduction)
2. [Exercises](#exercises)
   * [Exercise 1: Concatenation](#exercise-1-concatenation)
   * [Exercise 2: `format()`](#exercise-2-format)
   * [Exercise 3: f-string](#exercise-3-f-string)
3. [Solutions](#solutions)
   * [Exercise 1: Concatenation](#exercise-1-concatenation)
   * [Exercise 2: `format()`](#exercise-2-format)
   * [Exercise 3: f-string](#exercise-3-f-string)

## Introduction

Print statements play a crucial role in conveying information and messages within Python code. A well-organised and informative print statement not only communicates essential details but also enhances the overall quality of code.

Importance and benefits:

1. **Improved readability**: Well-structured print statements make code more readable, allowing developers to quickly understand the purpose of each print statement.
2. **Enhanced debugging**: Informative print statements facilitate debugging by providing insight into the state of variables or the flow of program execution at specific points.
3. **Facilitates collaboration**: Clear print statements make it easier for team members to comprehend and contribute to the codebase, promoting collaboration among developers.
4. **Documentation aid**: Print statements serve as a form of documentation, offering insights into the program's behaviour and helping developers understand the code without delving into details.
5. **Communicate with users**: Messages displayed through print statements offer users insights into the program's progress and results, making the application more user-friendly.

The three common methods used for string formatting in Python are:
* Concatenation.
* The `format()` method.
* F-strings.

## Exercises

### Exercise 1: Concatenation

Given the name of a forest (`forest_name`), the area covered by the forest (`area`), and the type of forest (`forest_type`),
use concatenation to print a statement in the format: "The Mau Forest is the largest closed‐canopy montane forest ecosystem in East Africa, covering 400000 hectares."

**HINT**: Use the `+` operator to concatenate a variable and string within a print statement.
"""

# Given the following variables
forest_name = "Mau Forest"
area = 400000
forest_type = "closed‐canopy montane"

print("The"+" "+forest_name+" "+"is the largest"+" "+forest_type+" "+"forest ecosystem in East Africa,"+" "+"covering"+" "+str(area)+" "+ "hectares.")

"""### Exercise 2: `format()`

#### Introduction

The `format()` method is a built-in string method in Python that allows us to format strings by inserting values into placeholders. The general syntax is:


`formatted_string = "This is a string where we display two values: {} and {}.".format(value1, value2)`

In this syntax, `{}` are placeholders that will be replaced by the values passed to the `format()` method. The variables are inserted into the string in the order that they are listed in the `format()` method.

The `format()` function is particularly handy when we want to create dynamic strings with variable content. It helps improve code readability and maintainability by separating the string structure from the actual values. Strings can be saved in variables and printed later, or they can be created in the `print()` statement itself.

#### Task

Given the annual growth rate of trees (`growth_rate`) and the region of the forest (`forest_region`), use the `format()` method to print a statement in the format: "The annual growth rate of trees in the Amazon forest is 2.5%."
"""

# Given the following variables
growth_rate = 2.5
forest_region = "Amazon"

print("The annual growth rate of trees in the {} forest is {}%.".format(forest_region, growth_rate))

"""### Exercise 3: F-string

#### Introduction

F-strings, or formatted string literals, provide a concise and convenient way to embed expressions inside string literals. Introduced in Python 3.6, f-strings make string formatting more readable and expressive.

An f-string is a string literal prefixed with `'f'` or `'F'`. It allows us to embed expressions inside curly braces `{}` within the string, and these expressions will be evaluated and formatted at runtime.

`formatted_string = f"{value1} and {value2} are displayed using an f-string." `

A benefit of using f-strings is that the code is **easy to interpret due to the variable names being displayed in the string itself**, compared to the `format()` method where the variable names are bunched at the end of the string.

#### Task
Given the concept of sustainable forest management (`sfm_concept`) and the importance of biodiversity (`biodiversity_importance`), use an f-string to print a statement in the format: "Sustainable Forest Management is crucial for maintaining biodiversity."
"""

# Given the following variables
sfm_concept = "Sustainable Forest Management"
biodiversity_importance = "maintaining biodiversity"

print(f"{sfm_concept} is crucial for {biodiversity_importance}.")

"""## Solutions

### Exercise 1: Concatenation
"""

# Exercise 1 Solution:
# Given the following variables
forest_name = "Mau Forest"
area = 400000
forest_type = "closed‐canopy montane"

# Use concatenation to print a statement
print("The " + forest_name + " is the largest " + forest_type + " forest ecosystem in East Africa, covering " + str(area) + " hectares.")

"""### Exercise 2: `format()`

"""

# Given the following variables
growth_rate = 2.5
forest_region = "Amazon"

# Use the format() method to print a statement
print("The annual growth rate of trees in the {} forest is {}%.".format(forest_region, growth_rate))

"""### Exercise 3: F-string"""

# Given the following variables
sfm_concept = "Sustainable Forest Management"
biodiversity_importance = "maintaining biodiversity"

# Use f-strings to print a statement
print(f"{sfm_concept} is crucial for {biodiversity_importance}.")

"""Using an f-string is a fast and clean way to format strings containing variables, while simultaneously keeping the code readable. It is often considered as the preferred way to create print statements.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>
"""